name: Frug Report
description: File a frug report
title: "[Frug]: "
labels: ["frug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for filing a frug report!
  - type: textarea
    id: what-happened
    attributes:
      label: Explain the problem.
      description: What happened? What did you expect to happen?
      placeholder: What went wrong?
    validations:
      required: true
  - type: textarea
    id: reproducer
    attributes:
      label: Reproducer
      description: Please provide instructions to reproduce the problem.
      placeholder: |
        Clone the repo on github.com/example/example and do XYZ
    validations:
      required: true
  - type: input
    id: spimdisasm-version
    attributes:
      label: spimdisasm version
      description: What version of spimdisasm are you running? (`spimdisasm --version`)
    validations:
      required: true
  - type: input
    id: splat-version
    attributes:
      label: [Optional] splat version
      description: What version of splat are you running?
    validations:
      required: false
  - type: textarea
    id: other-version
    attributes:
      label: [Optional] Version of other stuff
      description: Here you can put the version of whatever other software you think may be relevant, like Python, rabbitizer, binutils, OS, etc.
      placeholder: |
        Python: 4.18
        rabbitizer: 72.½
        binutils: 2.π
        Wine on WSL2 on Windows 11 on VirtualBox on OpenBSD machine.
        Etc
    validations:
      required: false
