name: Check mypy

# Build on every branch push, tag push, and pull request change:
on: [push, pull_request]

jobs:
  checks:
    runs-on: ubuntu-latest
    name: mypy
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Setup venv
        run: |
          python3 -m venv .venv
          . .venv/bin/activate

      - name: Install Dependencies
        run: |
          python3 -m pip install -U -r requirements.txt
          python3 -m pip install -U mypy

      - name: mypy
        run: mypy --show-column-numbers --hide-error-context .
